### ISSUE TITLE
Collision detection bug - 1

### ISSUE THREAD

**Issue by akshatjain02** [akshatjain02/Breakout#1]
The collision detection function has to be improved because the ball reflects off of a brick only after it is halfway into the brick.

**Comment by enginmanap** [comment]
Hey,

do you expect help in hacktoberfest context, or you plan to implement these issues yourself?

**Comment by akshatjain02** [comment]
Hi @enginmanap !
I plan on implementing these particular issues myself. But I'll soon be opening new issues for which I expect external help. You can resolve those issues.
