### ISSUE TITLE
Reflection of ball from paddle should be at different angle depending on where it hits the paddle.

### ISSUE THREAD

**Issue by akshatjain02** [akshatjain02/Breakout#7]

**Comment by orangeullr** [comment]
Should it the angle be less than or greater than the current reflection if it's on the outside of the paddle?

**Comment by akshatjain02** [comment]
Greater.
I made some changes and made it such way that is reflects to right when ball  hits right half of paddle, and reflects to left of ball hits left half of paddle. You can try to make the reflection vary linearly on the paddle. Make a PR and I'll merge it.
